apiVersion: build.knative.dev/v1alpha1
kind: BuildTemplate
metadata:
  name: jenkins-go
spec:
  timeout: 60m
  steps:
  - env:
    - name: GIT_COMMITTER_EMAIL
      value: jenkins-x@googlegroups.com
    - name: GIT_AUTHOR_EMAIL
      value: jenkins-x@googlegroups.com
    - name: GIT_AUTHOR_NAME
      value: jenkins-x-bot
    - name: GIT_COMMITTER_NAME
      value: jenkins-x-bot
    - name: XDG_CONFIG_HOME
      value: /home/jenkins
    - name: DOCKER_CONFIG
      value: /home/jenkins/.docker/
    - name: _JAVA_OPTIONS
      value: "-Xmx400m"
    - name: BUILD_NUMBER
      value: $BUILD_ID
    - name: DOCKER_REGISTRY
      valueFrom:
        configMapKeyRef:
          key: docker.registry
          name: jenkins-x-docker-registry
    image: jenkinsxio/jenkins-go:{{ .Values.jenkinsTag }}
    name: "jenkins"
    resources:
      limits:
        cpu: 3
        memory: 5Gi
      requests:
        cpu: "0.5"
        memory: 1Gi
    volumeMounts:
    - mountPath: /home/jenkins/.docker
      name: jenkins-docker-cfg
    - mountPath: /var/run/docker.sock
      name: docker-sock-volume
  volumes:
  - name: jenkins-docker-cfg
    secret:
      secretName: jenkins-docker-cfg
  - hostPath:
      path: /var/run/docker.sock
    name: docker-sock-volume
